site_name: 'Microsoft - IdFix'
docs_dir: 'docs'
nav:
  - Overview: 'Overview.md'
  - 'Prerequisites': 'Step 1 - Review the prerequisites.md'
  - 'Install IdFix': 'Step 2 - Install IdFix.md'
  - 'Query and fix invalid attibutes': 'Step 3 - Query and fix invalid attributes.md'
  - 'Errors supported by the IdFix tool': 'Errors supported by the IdFix tool.md'
  - 'Frequently asked questions.': 'Frequently asked questions (FAQ).md'
  - 'Build Documentation': 'build-docs.md'
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
  logo: 'img/microsoft-365-logo.png'
  feature:
    tabs: true
extra_css:
  - 'css/extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
plugins:
  - search
  - markdownextradata
repo_url: https://github.com/microsoft/idfix
site_url: https://microsoft.github.io/idfix
